import json


def build_meal_explanation_data(meal_package):
    if not isinstance(meal_package, dict):
        raise ValueError("Meal package must be a dictionary")

    if meal_package.get("status") != "meal_ready":
        raise ValueError("Meal explanation requires a ready deterministic meal")

    meal = meal_package.get(
        "meal"
    )

    if not isinstance(meal, dict):
        raise ValueError("Meal package requires meal data")

    foods = meal.get(
        "foods",
        []
    )

    return {
        "meal_fraction": meal_package["meal_fraction"],
        "daily_target": meal_package["daily_target"],
        "meal_target": meal_package["meal_target"],
        "meal_summary": {
            "selected_food_count": len(
                foods
            ),
            "total_calories": meal["total_calories"],
            "total_protein_g": meal["total_protein_g"],
            "total_carbs_g": meal["total_carbs_g"],
            "total_fat_g": meal["total_fat_g"],
            "protein_target_met": meal["protein_target_met"],
            "calorie_target_met": meal["calorie_target_met"],
            "carb_target_met": meal["carb_target_met"],
            "fat_target_met": meal["fat_target_met"]
        },
        "safety": {
            "allergy_filter_applied": True,
            "safe_food_validation_passed": True
        }
    }


def build_meal_system_prompt():
    return "\n".join(
        [
            "You are the AI-Fitness meal explanation assistant.",
            "",
            "STRICT RULES",
            "1. The meal was already generated by deterministic AI-Fitness nutrition code.",
            "2. Do not calculate a replacement meal.",
            "3. Do not change calories, protein, carbohydrates, fat, meal fraction, or target-status values.",
            "4. Do not name, add, remove, substitute, or recommend food items.",
            "5. The actual structured food list is displayed separately by the application.",
            "6. Allergy filtering was performed by deterministic application code before this explanation.",
            "7. Do not suggest bypassing allergy restrictions.",
            "8. This is not a scientific research route.",
            "9. Do not invent research citations or citation markers such as [P001].",
            "10. Do not make medical claims.",
            "11. Explain only how the generated meal compares with its deterministic meal targets.",
            "12. Keep the explanation concise."
        ]
    )


def build_meal_user_prompt(question, meal_package):
    if not isinstance(question, str) or not question.strip():
        raise ValueError("Question must be a non-empty string")

    explanation_data = build_meal_explanation_data(
        meal_package
    )

    serialized = json.dumps(
        explanation_data,
        ensure_ascii=False,
        indent=2,
        sort_keys=True
    )

    return "\n".join(
        [
            "CURRENT USER REQUEST",
            question.strip(),
            "",
            "VERIFIED DETERMINISTIC MEAL SUMMARY",
            serialized,
            "",
            "IMPORTANT",
            "The application will display the actual foods separately.",
            "Do not name or recommend foods.",
            "Explain only the meal's calorie and macro alignment with the supplied targets."
        ]
    )


def build_meal_explanation_prompts(question, meal_package):
    return {
        "system_prompt": build_meal_system_prompt(),
        "user_prompt": build_meal_user_prompt(
            question,
            meal_package
        )
    }