def format_number(value):
    if isinstance(value, bool):
        return str(value)

    if isinstance(value, int):
        return str(value)

    if isinstance(value, float):
        if value.is_integer():
            return str(int(value))

        return str(round(value, 2))

    return str(value)


def build_meal_provider_fallback(meal_package):
    if not isinstance(meal_package, dict):
        raise ValueError("Meal package must be a dictionary")

    if meal_package.get("status") != "meal_ready":
        raise ValueError("Meal provider fallback requires a ready meal")

    meal_target = meal_package.get("meal_target")
    meal = meal_package.get("meal")

    if not isinstance(meal_target, dict):
        raise ValueError("Meal provider fallback requires meal target data")

    if not isinstance(meal, dict):
        raise ValueError("Meal provider fallback requires meal result data")

    target_calories = format_number(
        meal_target["calorie_target"]
    )

    target_protein = format_number(
        meal_target["protein_g"]
    )

    total_calories = format_number(
        meal["total_calories"]
    )

    total_protein = format_number(
        meal["total_protein_g"]
    )

    return (
        "Your meal was successfully generated by the deterministic AI-Fitness "
        f"nutrition system. Its target was about {target_calories} calories and "
        f"{target_protein} g of protein, and the generated meal contains about "
        f"{total_calories} calories and {total_protein} g of protein. "
        "The structured food list remains available in the meal result. "
        "The optional AI explanation is temporarily unavailable."
    )


def build_workout_provider_fallback(workout_package):
    if not isinstance(workout_package, dict):
        raise ValueError("Workout package must be a dictionary")

    if workout_package.get("status") != "workout_ready":
        raise ValueError("Workout provider fallback requires a ready workout")

    selected_count = workout_package.get(
        "selected_exercise_count"
    )

    candidate_count = workout_package.get(
        "candidate_exercise_count"
    )

    action = workout_package.get(
        "workout_action"
    )

    if not isinstance(selected_count, int):
        raise ValueError("Workout package requires selected exercise count")

    if not isinstance(candidate_count, int):
        raise ValueError("Workout package requires candidate exercise count")

    action_text = (
        "weekly workout"
        if action == "weekly_workout"
        else "workout"
    )

    return (
        f"Your {action_text} was successfully generated by the deterministic "
        f"AI-Fitness workout system. The plan contains {selected_count} selected "
        f"exercise entries drawn from {candidate_count} compatible candidate "
        "exercises after the application's profile and safety filters were applied. "
        "The full structured workout remains available in the workout result. "
        "The optional AI explanation is temporarily unavailable."
    )