import json


PRESCRIPTION_FIELDS = (
    "order",
    "exercise_order",
    "category",
    "exercise_type",
    "primary_muscle",
    "sets",
    "reps",
    "rep_range",
    "duration_seconds",
    "duration_minutes",
    "rest_seconds",
    "rir_target",
    "rpe_target"
)


PLAN_METADATA_FIELDS = (
    "status",
    "fits_session",
    "estimated_duration_minutes",
    "total_duration_minutes",
    "session_duration_minutes",
    "warm_up_minutes",
    "cool_down_minutes",
    "training_days_per_week"
)


def find_first_value(value, field_name):
    if isinstance(value, dict):
        if field_name in value:
            return value[field_name]

        for child in value.values():
            result = find_first_value(
                child,
                field_name
            )

            if result is not None:
                return result

    if isinstance(value, (list, tuple)):
        for child in value:
            result = find_first_value(
                child,
                field_name
            )

            if result is not None:
                return result

    return None


def extract_prescription_summaries(value):
    summaries = []

    def visit(current):
        if isinstance(current, dict):
            if "exercise_id" in current:
                summary = {}

                for field in PRESCRIPTION_FIELDS:
                    if field in current:
                        summary[field] = current[field]

                summaries.append(summary)

            for child in current.values():
                visit(child)

        elif isinstance(current, (list, tuple)):
            for child in current:
                visit(child)

    visit(value)

    return summaries


def build_workout_explanation_data(workout_package):
    if not isinstance(workout_package, dict):
        raise ValueError("Workout package must be a dictionary")

    if workout_package.get("status") != "workout_ready":
        raise ValueError("Workout explanation requires a ready deterministic workout")

    plan = workout_package.get("workout_plan")

    if not isinstance(plan, dict):
        raise ValueError("Workout package requires deterministic workout plan data")

    metadata = {}

    for field in PLAN_METADATA_FIELDS:
        value = find_first_value(
            plan,
            field
        )

        if value is not None:
            metadata[field] = value

    return {
        "workout_action": workout_package["workout_action"],
        "candidate_exercise_count": workout_package["candidate_exercise_count"],
        "selected_exercise_count": workout_package["selected_exercise_count"],
        "requested_exercise_count": workout_package["requested_exercise_count"],
        "plan_metadata": metadata,
        "exercise_prescriptions": extract_prescription_summaries(
            plan
        ),
        "safety": {
            "candidate_filter_applied": True,
            "candidate_safety_validation_passed": True,
            "exercise_selection_performed_by_llm": False
        }
    }


def build_workout_system_prompt():
    return "\n".join(
        [
            "You are the AI-Fitness workout explanation assistant.",
            "",
            "STRICT RULES",
            "1. The workout was already generated by deterministic AI-Fitness workout code.",
            "2. Do not choose, add, remove, replace, reorder, or substitute exercises.",
            "3. Do not create a replacement workout.",
            "4. Do not change sets, reps, rest periods, RIR, RPE, duration, or other prescription values.",
            "5. The actual exercise names and structured plan are displayed separately by the application.",
            "6. Exercise eligibility was determined before generation using the application's environment, equipment, preference, limitation, and difficulty rules.",
            "7. Do not override a limitation or unavailable-equipment decision.",
            "8. Do not diagnose pain or injuries.",
            "9. This is not a scientific research route.",
            "10. Do not invent research citations or citation markers such as [P001].",
            "11. Explain only the structure and intent of the deterministic workout.",
            "12. Keep the explanation concise."
        ]
    )


def build_workout_user_prompt(question, workout_package):
    if not isinstance(question, str) or not question.strip():
        raise ValueError("Question must be a non-empty string")

    explanation_data = build_workout_explanation_data(
        workout_package
    )

    serialized = json.dumps(
        explanation_data,
        ensure_ascii=False,
        indent=2,
        sort_keys=True,
        default=str
    )

    return "\n".join(
        [
            "CURRENT USER REQUEST",
            question.strip(),
            "",
            "VERIFIED DETERMINISTIC WORKOUT SUMMARY",
            serialized,
            "",
            "IMPORTANT",
            "The application will display exercise names and the full structured workout separately.",
            "Do not invent exercise names.",
            "Do not modify the plan.",
            "Explain only the supplied deterministic structure and prescription."
        ]
    )


def build_workout_explanation_prompts(question, workout_package):
    return {
        "system_prompt": build_workout_system_prompt(),
        "user_prompt": build_workout_user_prompt(
            question,
            workout_package
        )
    }